
CREATE DATABASE Pessoas;



USE Pessoas;



CREATE TABLE Pessoas (IdPessoa INT IDENTITY PRIMARY KEY, NomePessoa VARCHAR (255) NOT NULL)


CREATE TABLE Telefones(IdTelefone INT IDENTITY PRIMARY KEY ,Descricao VARCHAR (255) NOT NULL ,IdPessoa INT FOREIGN KEY REFERENCES Pessoas (IdPessoa) NOT NULL)



CREATE TABLE Email(IdEmail INT IDENTITY PRIMARY KEY, Descricao VARCHAR (255) NOT NULL, IdPessoa INT FOREIGN KEY REFERENCES Pessoas (IdPessoa) NOT NULL)


CREATE TABLE CNHs(IdCNH INT IDENTITY PRIMARY KEY, Descricao VARCHAR (255) NOT NULL, IdPessoa INT FOREIGN KEY REFERENCES Pessoas (IdPessoa) NOT NULL)

