CREATE DATABASE Clinica
USE Clinica

CREATE TABLE Clinica(IdClinica INT IDENTITY PRIMARY KEY, RazaoSocial varchar(200), Endereco varchar(200))

CREATE TABLE Dono(IdDono INT IDENTITY PRIMARY KEY, NomeDono varchar(200))

CREATE TABLE TipoPet(IdTipoPet INT IDENTITY PRIMARY KEY, TituloPet varchar(200))

CREATE TABLE VETERINARIO(IdVeterinario INT IDENTITY PRIMARY KEY, NomeVet varchar(200), CRMV INT, IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica))

CREATE TABLE Raca(IdRaca INT IDENTITY PRIMARY KEY, TituloRaca varchar(200), IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet))

CREATE TABLE Pet (IdPet INT IDENTITY PRIMARY KEY, Nome varchar(200), Telefone varchar(200), 
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono), IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca))

CREATE TABLE ATENDIMENTO  (IdAtendimento INT IDENTITY PRIMARY KEY, DataAtendimento DATE, Descricao varchar(1000), 
IdVet INT FOREIGN KEY REFERENCES VETERINARIO(IdVeterinario), IdPet INT REFERENCES Pet(IdPet))
