SELECT IdAtendimento, DataAtendimento, Descricao, VETERINARIO.NomeVet, Pet.Nome FROM ATENDIMENTO
INNER JOIN VETERINARIO ON ATENDIMENTO.IdVet=VETERINARIO.IdVeterinario
INNER JOIN Pet ON ATENDIMENTO.IdPet=Pet.IdPet